#!/bin/sh

docker run \
--rm \
-d \
--name nginx-vm-img \
--env "LETSENCRYPT_HOST=workervm.seal.purdue.wtf" \
--env "LETSENCRYPT_EMAIL=santiagotorres@purdue.edu" \
--env "VIRTUAL_HOST=workervm.seal.purdue.wtf" \
--network purdue-monitor \
nginx-vm-img
