#!/bin bash
docker run --name vmrebuilderd \
    -it --device=/dev/kvm:/dev/kvm:rwm \
    --mount type=volume,source=vmrebuilderd,destination=/vm/ \
    -p 10022:10022 \
    --publish 5800 \
    --publish 5900 \
    virtualized_worker
